Repository Abby3017/discussionForum, pull requests merged in 2019-04, with the labels that each got.

#28 App 2019
  content/eng/manifesto/aap_2019.md
Labels: size/L

#26 add i18n
  content/eng/manifesto/aap_2019.md
  i18n/en.yaml
  static/css/style.css
Labels: size/M

#30 add check on backToTop and readme update
  README.md
  config.toml
  layouts/_default/baseof.html
  static/css/style.css
  static/favicon.ico
Labels: enhancement

#31 translation css change
  content/eng/manifesto/aap_2014.md
  content/eng/manifesto/aap_2019.md
  content/eng/manifesto/bjp_2014.md
  content/eng/manifesto/bjp_2019.md
  layouts/partials/head.html
  layouts/partials/header.html
  static/css/site_styles.css
  static/css/style.css
Labels: size/L
